apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-data-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: slow

