apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server-deployment
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      containers:
      - name: minecraft-server
        image: itzg/minecraft-server:latest
        env:
        - name: EULA
          value: "true"
        - name: PVP
          value: "false"
        ports:
        - containerPort: 25565
        volumeMounts:
        - mountPath: /data
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: minecraft-server-data-pvc

